### ISSUE TITLE
”issueベースの開発”レビュー依頼

### ISSUE THREAD

**Issue by seki221** [seki221/graduation-exam#14]
■Webアプリの概要
このWebアプリの説明を500文字以下で記載してください。

このアプリは、ユーザーが旅行の行き先やスケジュールを管理する為のツールです。旅行の計画をして訪れた記録を行い、旅の思い出を整理することを主な目的としています。
このサービスでは目的地、日程、費用、交通手段などの情報を入力でき、記録した予定がカード形式で表示されるため、見やすく整理された形で一覧を確認することが可能です。またタグ付けなどによっても探しやすくなっています
また各イベントごとに「レビュー」も付けることができます。これは、訪れた場所の印象などを文字通り評価（レビュー）する形で残せるもので、旅行ごとに複数のレビューを追加することも可能です。自らの感想や先述の各種情報による記録が将来的に過去の旅行を振り返る際にも役立ちます。
また、お気に入り機能を設けており、気になるスポットや訪れたい場所をリスト化してあり再訪の計画を立てる際にも役立つ、シンプルで便利なツールです。

■1週間辺りの開発に向けられる時間
- 1週間あたり：26時間

（ストーリポイント1消費するのに2時間を目安として、1週間あたりどれだけストーリポイントを消化できるか確認してください）

■ProjectsのURL
作成したProjects（看板・issue・ストーリーポイントが確認できるもの且つ他者でも閲覧可能状態）のURLを貼り付けてください。
https://github.com/users/seki221/projects/1
■MVPリリースまで
- [x] rails new
- [x] herokuにデプロイ
- [x] トップページ
- [x] ユーザー登録機能
- [x] ログイン機能
- [x] メインページ
- [x] 一覧表示
- [ ] 投稿機能（CRUD）

■MVP後
- [ ] 検索機能
>- [ ] 結果表示ページ
- [ ] ブックマーク機能
- [ ] オートコンプリート検索機能
- [ ] タグ付け
- [ ] レビュー機能
- [ ] 時系列リスト
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] パスワードリセット機能
- [ ] メアド更新
- [ ] RSpec（モデルテスト・システムテスト）
- [ ] レスポンシブ対応

■MVPレビュー依頼予定日
予定日：2024年 12月 25日

**Comment by seki221** [comment]
残りCRUDのdだけだが難航

**Comment by TakenakaEri** [comment]
お疲れ様です。

こちら、既に開発がほとんど終わっている段階で提出されているということでしょうか？
通常であれば、こちらはアプリ制作の前に提出をしていただく課題となります。

既に作成済みの項目が多数あるためLGTMを出しますが、開発の方法としては誤っているため、次回からは注意して下さい。（MVPが終わった後に本リリースまででも同様の手続きを踏んで本リリースまで実装するため、次回は先に出すようにして下さい）

**Comment by seki221** [comment]
失礼しました
開発初期に提出したはずなのですが反応が無く(覚えて無いですが提出後何か通知文字が出た記憶がありますが)
こちらの手違いではあると思ったので改めて提出しました
